# spark 基本参数配置
spark.basic:
  appName: spark-batch
  # master
  master: local[2]

# spark 参数配置
spark.streaming:
  # spark streaming 功能列表
  functions:
  - clazzName: com.tiantao.spark.batch.handler.impl.TestHandler
    desc: "测试"
    params: 1,2,3,4,5,6,7,8,9,0
  - clazzName: com.tiantao.spark.batch.handler.impl.TestHandler
    desc: "测试"
    params: aaaaaaaa,10,11,12,13,14,15,16,17,18,19.20